<#-- @ftlvariable name="schema" type="java.lang.String" -->
CREATE MULTISET TABLE ${schema}.T_REPORT_FILTER,
NO FALLBACK,
NO BEFORE JOURNAL,
NO AFTER JOURNAL,
CHECKSUM = DEFAULT,
DEFAULT MERGEBLOCKRATIO
(
    JOB_ID INTEGER,
    REPORT_FILTER_NAME VARCHAR(255) CHARACTER SET UNICODE CASESPECIFIC,
    FILTER_GROUP_NAME VARCHAR(255) CHARACTER SET UNICODE CASESPECIFIC,
    FILTER_TYPE VARCHAR(255) CHARACTER SET UNICODE CASESPECIFIC,
    OPERATION_TYPE VARCHAR(255) CHARACTER SET UNICODE CASESPECIFIC
) NO PRIMARY INDEX ;
