<#-- @ftlvariable name="schema" type="java.lang.String" -->
CREATE MULTISET TABLE ${schema}.T_REPORT_FILTER_FIELD_VALUE,
NO FALLBACK,
NO BEFORE JOURNAL,
NO AFTER JOURNAL,
CHECKSUM = DEFAULT,
DEFAULT MERGEBLOCKRATIO
(
    JOB_ID INTEGER,
    report_filter_field_id INTEGER,
    TUPLE_ID INTEGER,
    VARCHAR_VALUE VARCHAR(255) CHARACTER SET UNICODE CASESPECIFIC,
    DATE_VALUE DATE,
    INTEGER_VALUE INTEGER,
    DOUBLE_VALUE DOUBLE PRECISION
) NO PRIMARY INDEX;
