INSERT INTO T_RF_REGION (region_code,region_name) VALUES (89,'Ямало-Ненецкий автономный округ');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (27,'Хабаровский край');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (29,'Архангельская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (45,'Курганская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (72,'Тюменская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (30,'Астраханская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (54,'Новосибирская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (34,'Волгоградская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (26,'Ставропольский край');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (66,'Свердловская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (37,'Ивановская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (56,'Оренбургская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (73,'Ульяновская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (63,'Самарская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (9,'Карачаево-Черкесская республика');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (53,'Новгородская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (79,'Еврейская автономная область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (5,'Республика Дагестан');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (51,'Мурманская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (21,'Чувашская республика');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (36,'Воронежская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (82,'Республика Крым');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (83,'Ненецкий автономный округ');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (50,'Московская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (14,'Республика Саха (Якутия)');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (43,'Кировская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (8,'Республика Калмыкия');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (35,'Вологодская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (22,'Алтайский край');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (64,'Саратовская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (75,'Забайкальский край');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (25,'Приморский край');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (17,'Республика Тыва');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (11,'Республика Коми');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (86,'Ханты-Мансийский автономный округ - Югра');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (92,'Севастополь');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (87,'Чукотский автономный округ');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (13,'Республика Мордовия');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (39,'Калининградская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (6,'Республика Ингушетия');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (15,'Республика Северная Осетия - Алания');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (4,'Республика Алтай');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (49,'Магаданская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (65,'Сахалинская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (44,'Костромская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (60,'Псковская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (28,'Амурская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (46,'Курская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (58,'Пензенская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (12,'Республика Марий Эл');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (77,'Москва');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (55,'Омская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (76,'Ярославская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (69,'Тверская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (48,'Липецкая область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (19,'Республика Хакасия');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (70,'Томская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (62,'Рязанская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (57,'Орловская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (1,'Республика Адыгея');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (95,'Чеченская республика');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (68,'Тамбовская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (24,'Красноярский край');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (3,'Республика Бурятия');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (31,'Белгородская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (40,'Калужская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (38,'Иркутская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (33,'Владимирская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (59,'Пермский край');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (32,'Брянская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (71,'Тульская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (10,'Республика Карелия');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (61,'Ростовская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (18,'Удмуртская республика');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (74,'Челябинская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (67,'Смоленская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (7,'Кабардино-Балкарская республика');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (78,'Санкт-Петербург');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (23,'Краснодарский край');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (52,'Нижегородская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (2,'Республика Башкортостан');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (42,'Кемеровская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (47,'Ленинградская область');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (16,'Республика Татарстан');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (41,'Камчатский край');
INSERT INTO T_RF_REGION (region_code,region_name) VALUES (94,'Байконур');
